server:
  port: 9003

spring:
  datasource:
    name: xcbilling
    url: jdbc:mysql://localhost:3306/collecttool?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://localhost:3306/xcbilling?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: collecttool

mybatis:
  #实体类所做包
  type-aliases-package: learning.pojo
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
