server:
  port: 8081

spring:
  application:
    name: geteway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时

ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
#zuul:
#  routes:
#    weixin: /wxt/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
